# Generated by Django 4.1.7 on 2023-04-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_puppy_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePet', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=20)),
                ('raca', models.CharField(max_length=20)),
                ('dtNasc', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=1)),
                ('peso', models.FloatField(blank=True, max_length=5, null=True)),
                ('porte', models.CharField(max_length=20)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('cadAtivo', models.BooleanField(default=True)),
            ],
        ),
    ]
