# Generated by Django 4.2 on 2023-04-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_puppy_core', '0002_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='peso',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
