# Generated by Django 4.2 on 2023-04-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_puppy_core', '0003_alter_pet_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='foto',
        ),
    ]
