# Generated by Django 4.2 on 2023-04-11 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_puppy_core', '0005_alter_pet_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_puppy_core.tutor'),
            preserve_default=False,
        ),
    ]
