# Generated by Django 4.2 on 2023-04-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_puppy_core', '0008_cartaovacina'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaovacina',
            name='nomeVeterinario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
