# Generated by Django 4.2 on 2023-04-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_puppy_core', '0009_cartaovacina_nomeveterinario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaovacina',
            name='dataVacina',
            field=models.DateField(blank=True),
        ),
    ]
