# Generated by Django 4.2 on 2023-04-27 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_puppy_core', '0010_alter_cartaovacina_datavacina'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoExames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame', models.CharField(max_length=100)),
                ('nomeVeterinario', models.CharField(max_length=100)),
                ('dataSolicitacao', models.DateField()),
                ('dataResultado', models.DateField(blank=True)),
                ('resultado', models.FileField(upload_to='resultados/')),
                ('pet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_puppy_core.pet')),
            ],
        ),
    ]
