# Generated by Django 4.2.1 on 2023-05-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_puppy_core', '0015_alter_cartaovacina_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeVacina', models.CharField(max_length=100)),
                ('dataVacina', models.DateField()),
                ('vetResponsavel', models.CharField(max_length=100)),
            ],
        ),
    ]
