# Generated by Django 4.2 on 2023-06-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_puppy_core', '0016_vacinacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaoexames',
            name='resultado',
            field=models.CharField(max_length=500),
        ),
    ]
